set -e
true
true
/Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/bin/spades-core /Users/dz11/github/dd_2025/conda_practice/spades_output/K21/configs/config.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K21/configs/mda_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K21/configs/meta_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K21/configs/rnaviral_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K21/configs/hmm_mode.info
/Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/bin/spades-core /Users/dz11/github/dd_2025/conda_practice/spades_output/K49/configs/config.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K49/configs/mda_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K49/configs/meta_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K49/configs/rnaviral_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K49/configs/hmm_mode.info
/Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/bin/spades-core /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/configs/config.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/configs/mda_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/configs/meta_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/configs/rnaviral_mode.info /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/configs/hmm_mode.info
/Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/bin/python3 /Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/share/spades/spades_pipeline/scripts/copy_files.py /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/before_rr.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/before_rr.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/assembly_graph_after_simplification.gfa /Users/dz11/github/dd_2025/conda_practice/spades_output/assembly_graph_after_simplification.gfa /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/final_contigs.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/raw_contigs.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/first_pe_contigs.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/first_pe_contigs.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/strain_graph.gfa /Users/dz11/github/dd_2025/conda_practice/spades_output/strain_graph.gfa /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/scaffolds.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/raw_scaffolds.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/scaffolds.paths /Users/dz11/github/dd_2025/conda_practice/spades_output/raw_scaffolds.paths /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/assembly_graph_with_scaffolds.gfa /Users/dz11/github/dd_2025/conda_practice/spades_output/assembly_graph_with_scaffolds.gfa /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/assembly_graph.fastg /Users/dz11/github/dd_2025/conda_practice/spades_output/assembly_graph.fastg /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/final_contigs.paths /Users/dz11/github/dd_2025/conda_practice/spades_output/contigs.paths /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/gene_clusters.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/scaffolds.fasta /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/hmm_statistics.txt /Users/dz11/github/dd_2025/conda_practice/spades_output/hmm_statistics.txt /Users/dz11/github/dd_2025/conda_practice/spades_output/K75/domain_graph.dot /Users/dz11/github/dd_2025/conda_practice/spades_output/domain_graph.dot
true
/Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/bin/python3 /Users/dz11/homebrew/Caskroom/miniconda/base/envs/spades/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/dz11/github/dd_2025/conda_practice/spades_output/raw_scaffolds.fasta --misc_dir /Users/dz11/github/dd_2025/conda_practice/spades_output/misc --threshold_for_breaking_scaffolds 3
true
